Products = {
    'NewReleases': {
        'Sports & Outdoors': 'https://www.amazon.com/gp/new-releases/sporting-goods/',

        'Fan Shop': 'https://www.amazon.com/gp/new-releases/sporting-goods/3386071/',

        'Auto Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/374773011/',
        'Air Freshners': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769016011/',
        'Antenna Toppers': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769017011/',
        'Car Covers': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769018011/',
        'Car Flags': 'https://www.amazon.com/gp/new-releases/sporting-goods/374774011/',
        'Car Magnets': 'https://www.amazon.com/gp/new-releases/sporting-goods/374775011/',
        'Decals & Bumper Stickers': 'https://www.amazon.com/gp/new-releases/sporting-goods/3209245011/',
        'Emblems': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769019011/',
        'Floormats': 'https://www.amazon.com/gp/new-releases/sporting-goods/374776011/',
        'Key Chains': 'https://www.amazon.com/gp/new-releases/sporting-goods/374793011/',
        'License Plate Covers': 'https://www.amazon.com/gp/new-releases/sporting-goods/721262011/',
        'License Plate Frames': 'https://www.amazon.com/gp/new-releases/sporting-goods/721261011/',
        'Mirror Covers': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769021011/',
        'Seat Covers': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769022011/',
        'Splashguards': 'https://www.amazon.com/gp/new-releases/sporting-goods/374778011/',
        'Steering Wheel Covers': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769023011/',
        'Tire Covers': 'https://www.amazon.com/gp/new-releases/sporting-goods/374780011/',
        'Trailer Hitch Covers': 'https://www.amazon.com/gp/new-releases/sporting-goods/374781011/',
        'Windshield Sun Shades': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769024011/',

        'Bags, Packs & Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768574011/',
        'Backpacks': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768575011/',
        'Drawstring Bags': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768576011/',
        'Duffle Bags': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768577011/',
        'Laptop & Messenger Bags': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768578011/',
        'Luggage': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768581011/',
        'Luggage Tags': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768582011/',
        'Lunchboxes': 'https://www.amazon.com/gp/new-releases/sporting-goods/374878011/',
        'Tote Bags': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768583011/',
        'Wallets': 'https://www.amazon.com/gp/new-releases/sporting-goods/374745011/',
        'Women Handbags & Purses': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768584011/',

        'Toys Games': 'https://www.amazon.com/gp/new-releases/toys-and-games/',
        'Action, Toys & Figures': 'https://www.amazon.com/gp/new-releases/toys-and-games/165993011/',
        'Action Figures': 'https://www.amazon.com/gp/new-releases/toys-and-games/2514571011/',
        'Video Games': 'https://www.amazon.com/gp/new-releases/videogames/',
        'Play Station 4': 'https://www.amazon.com/gp/new-releases/videogames/6427814011/',
        'Accessories': 'https://www.amazon.com/gp/new-releases/videogames/6427815011/',
        'Baby': 'https://www.amazon.com/gp/new-releases/baby-products/',
        'BathingSkinCare': 'https://www.amazon.com/gp/new-releases/baby-products/166736011/',
        'Aromatherapy': 'https://www.amazon.com/gp/new-releases/baby-products/322258011/'
    },
    'BestSellers': {
        'SportsOutdoors': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors/zgbs/sporting-goods/',
        'FanShop': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Shop/zgbs/sporting-goods/3386071/',
        'AutoAccessories': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Auto-Accessories/zgbs/sporting-goods/374773011/',
        'ToysGames': 'https://www.amazon.com/Best-Sellers-Toys-Games/zgbs/toys-and-games/',
        'ActionToysFigures': 'https://www.amazon.com/Best-Sellers-Toys-Games-Toy-Figures-Playsets/zgbs/toys-and-games/165993011/',
        'ActionFigures': 'https://www.amazon.com/Best-Sellers-Toys-Games-Action-Toy-Figures/zgbs/toys-and-games/2514571011/',
        'VideoGames': 'https://www.amazon.com/best-sellers-video-games/zgbs/videogames/',
        'PlayStation4': 'https://www.amazon.com/Best-Sellers-Video-Games-PlayStation-Consoles-Accessories/zgbs/videogames/6427814011/',
        'Accessories': 'https://www.amazon.com/Best-Sellers-Video-Games-PlayStation-Accessories/zgbs/videogames/6427815011/',
        'Baby': 'https://www.amazon.com/Best-Sellers-Baby/zgbs/baby-products/',
        'BathingSkinCare': 'https://www.amazon.com/Best-Sellers-Baby-Bathing-Skin-Care/zgbs/baby-products/166736011/',
        'Aromatherapy': 'https://www.amazon.com/Best-Sellers-Baby-Aromatherapy/zgbs/baby-products/322258011/'
    }
}
