Products = {
    'NewReleases': {

         'Tablet Accessories': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Tablet-Accessories/zgbs/sporting-goods/13227293011/',
         'MP3 Player Accessories': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-MP3-Player-Accessories/zgbs/sporting-goods/3209248011/',
         'Computer Mousepads': 'https://www.amazon.com/gp/new-releases/sporting-goods/374849011/',
         'MP3 Player Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/3209248011/',
         'Tablet Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/13227293011/',
         'Computer Mousepads': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Computer-Mousepads/zgbs/sporting-goods/374849011/',
         'Computer Mice': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Computer-Mice/zgbs/sporting-goods/374848011/',
         'Computer Accessories': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Computer-Accessories/zgbs/sporting-goods/3318643011/', 

         'Auto Accessories': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Auto-Accessories/zgbs/sporting-goods/374773011/',
        'Air Fresheners': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Air-Fresheners/zgbs/sporting-goods/5769016011/',
        'Antenna Toppers': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Antenna-Toppers/zgbs/sporting-goods/5769017011/',
        'Car Covers': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Car-Covers/zgbs/sporting-goods/5769018011/',
        'Car Flags': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Car-Flags/zgbs/sporting-goods/374774011/',
        'Car Magnets': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Car-Magnets/zgbs/sporting-goods/374775011/',
        'Decals & Bumper Stickers': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Decals-Bumper-Stickers/zgbs/sporting-goods/3209245011/',
        'Emblems': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Emblems/zgbs/sporting-goods/5769019011/',
        'Floormats': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Floormats/zgbs/sporting-goods/374776011/',
        'Key Chains': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Key-Chains/zgbs/sporting-goods/374793011/',
        'License Plate Covers': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-License-Plate-Covers/zgbs/sporting-goods/721262011/',
        'License Plate Frames': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-License-Plate-Frames/zgbs/sporting-goods/721261011/',
        'Mirror Covers': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Mirror-Covers/zgbs/sporting-goods/5769021011/',
        'Seat Covers': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Seat-Covers/zgbs/sporting-goods/5769022011/',
        'Splashguards': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Splashguards/zgbs/sporting-goods/374778011/',
        'Steering Wheel Covers': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Steering-Wheel-Covers/zgbs/sporting-goods/5769023011/',
        'Tire Covers': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Tire-Covers/zgbs/sporting-goods/374780011/',
        'Trailer Hitch Covers': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Trailer-Hitch-Covers/zgbs/sporting-goods/374781011/',
        'Windshield Sun Shades': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Windshield-Sun-Shades/zgbs/sporting-goods/5769024011/',
        
        'Bags, Packs & Accessories': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Bags-Packs-Accessories/zgbs/sporting-goods/5768574011/',
        'Backpacks': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Backpacks/zgbs/sporting-goods/5768575011/',
        'Drawstring Bags': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Drawstring-Bags/zgbs/sporting-goods/5768576011/',
        'Duffle Bags': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Duffle-Bags/zgbs/sporting-goods/5768577011/',
        'Laptop & Messenger Bags': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Laptop-Messenger-Bags/zgbs/sporting-goods/5768578011/',
        'Luggage': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Luggage/zgbs/sporting-goods/5768581011/',
        'Luggage Tags': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Luggage-Tags/zgbs/sporting-goods/5768582011/',
        'Lunchboxes': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Lunchboxes/zgbs/sporting-goods/374878011/',
        'Tote Bags': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Tote-Bags/zgbs/sporting-goods/5768583011/',
        'Wallets': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Wallets/zgbs/sporting-goods/374745011/',
        'Womens Handbags & Purses': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Womens-Handbags-Purses/zgbs/sporting-goods/5768584011/',
        
        'Caps & Hats': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Caps-Hats/zgbs/sporting-goods/5768995011/',
        'Baseball Caps': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Baseball-Caps/zgbs/sporting-goods/374749011/',
        'Novelty Headwear': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Novelty-Headwear/zgbs/sporting-goods/2515124011/',
        'Scrub Caps': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Scrub-Caps/zgbs/sporting-goods/2515126011/',
        'Skullies & Beanies': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Skullies-Beanies/zgbs/sporting-goods/374752011/',
        'Visors': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Visors/zgbs/sporting-goods/374753011/',
        
        'Cell Phone Accessories': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Cell-Phone-Accessories/zgbs/sporting-goods/3209246011/',
        
        'Clothing': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Clothing/zgbs/sporting-goods/374742011/',
        'Jackets': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Jackets/zgbs/sporting-goods/3203998011/',
        'Jerseys': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Jerseys/zgbs/sporting-goods/3203999011/',
        'Pants': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Pants/zgbs/sporting-goods/3204000011/',
        'Polo Shirts': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Polo-Shirts/zgbs/sporting-goods/3204001011/ref=zg_bs_nav_sg_4_3204000011',
        'Shorts': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Shorts/zgbs/sporting-goods/3204002011/ref=zg_bs_nav_sg_4_3204001011',
        'Sweaters': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Sweaters/zgbs/sporting-goods/3204003011/ref=zg_bs_nav_sg_4_3204002011',
        'Sweatshirts & Hoodies': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Sweatshirts-Hoodies/zgbs/sporting-goods/3204004011/ref=zg_bs_nav_sg_4_3204003011',
        'T-Shirts': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Shirts/zgbs/sporting-goods/3204005011/ref=zg_bs_nav_sg_4_3204004011',
        'Baby Clothing': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Baby-Clothing/zgbs/sporting-goods/3204006011/ref=zg_bs_nav_sg_3_374742011',
        
        'Clothing Accessories': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Clothing-Accessories/zgbs/sporting-goods/2431377011/ref=zg_bs_nav_sg_2_3386071',
        'Belts': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Belts/zgbs/sporting-goods/5768996011/ref=zg_bs_nav_sg_3_2431377011',
        'Buckles': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Buckles/zgbs/sporting-goods/5768997011/ref=zg_bs_nav_sg_4_5768996011',
        'Caps & Hats': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Caps-Hats/zgbs/sporting-goods/5768995011/ref=zg_bs_nav_sg_4_5768997011',
        'Headbands': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Headbands/zgbs/sporting-goods/2515125011/ref=zg_bs_nav_sg_3_2431377011',
        'Sleeve Patches': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Sleeve-Patches/zgbs/sporting-goods/5768999011/ref=zg_bs_nav_sg_4_2515125011',
        'Socks': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Socks/zgbs/sporting-goods/3204007011/ref=zg_bs_nav_sg_4_5768999011',
        'Scarves': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Scarves/zgbs/sporting-goods/5768998011/ref=zg_bs_nav_sg_4_3204007011',
        'Sunglasses': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Sunglasses/zgbs/sporting-goods/374744011/ref=zg_bs_nav_sg_4_5768998011',
        'Ties': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Ties/zgbs/sporting-goods/374772011/ref=zg_bs_nav_sg_4_374744011',
        'Wristbands': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Wristbands/zgbs/sporting-goods/5769000011/ref=zg_bs_nav_sg_4_374772011',
        
        'Electronics': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Electronics/zgbs/sporting-goods/2311740011/ref=zg_bs_nav_sg_2_3386071',
        'Binoculars': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Binoculars/zgbs/sporting-goods/375521011/ref=zg_bs_nav_sg_3_2311740011',
        'Computer Mice': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Computer-Mice/zgbs/sporting-goods/374848011/ref=zg_bs_nav_sg_4_375521011',
        'Computer Mousepads': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Computer-Mousepads/zgbs/sporting-goods/374849011/ref=zg_bs_nav_sg_4_374848011',
        'Computer Accessories': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Computer-Accessories/zgbs/sporting-goods/3318643011/ref=zg_bs_nav_sg_4_374849011',
        'Headphones': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Headphones/zgbs/sporting-goods/3209247011/ref=zg_bs_nav_sg_4_3318643011',
        'MP3 Player Accessories': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-MP3-Player-Accessories/zgbs/sporting-goods/3209248011/ref=zg_bs_nav_sg_4_3209247011',
        'Tablet Accessories': 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Fan-Tablet-Accessories/zgbs/sporting-goods/13227293011/ref=zg_bs_nav_sg_4_3209248011',

        'Sports & Outdoors': 'https://www.amazon.com/gp/new-releases/sporting-goods/',

        'Fan Shop': 'https://www.amazon.com/gp/new-releases/sporting-goods/3386071/',

        'Auto Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/374773011/',
        'Air Freshners': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769016011/',
        'Antenna Toppers': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769017011/',
        'Car Covers': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769018011/',
        'Car Flags': 'https://www.amazon.com/gp/new-releases/sporting-goods/374774011/',
        'Car Magnets': 'https://www.amazon.com/gp/new-releases/sporting-goods/374775011/',
        'Decals & Bumper Stickers': 'https://www.amazon.com/gp/new-releases/sporting-goods/3209245011/',
        'Emblems': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769019011/',
        'Floormats': 'https://www.amazon.com/gp/new-releases/sporting-goods/374776011/',
        'Key Chains': 'https://www.amazon.com/gp/new-releases/sporting-goods/374793011/',
        'License Plate Covers': 'https://www.amazon.com/gp/new-releases/sporting-goods/721262011/',
        'License Plate Frames': 'https://www.amazon.com/gp/new-releases/sporting-goods/721261011/',
        'Mirror Covers': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769021011/',
        'Seat Covers': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769022011/',
        'Splashguards': 'https://www.amazon.com/gp/new-releases/sporting-goods/374778011/',
        'Steering Wheel Covers': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769023011/',
        'Tire Covers': 'https://www.amazon.com/gp/new-releases/sporting-goods/374780011/',
        'Trailer Hitch Covers': 'https://www.amazon.com/gp/new-releases/sporting-goods/374781011/',
        'Windshield Sun Shades': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769024011/',

        'Bags, Packs & Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768574011/',
        'Backpacks': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768575011/',
        'Drawstring Bags': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768576011/',
        'Duffle Bags': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768577011/',
        'Laptop & Messenger Bags': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768578011/',
        'Luggage': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768581011/',
        'Luggage Tags': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768582011/',
        'Lunchboxes': 'https://www.amazon.com/gp/new-releases/sporting-goods/374878011/',
        'Tote Bags': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768583011/',
        'Wallets': 'https://www.amazon.com/gp/new-releases/sporting-goods/374745011/',
        'Womens Handbags & Purses': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768584011/',

        'Caps & Hats': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768995011/',
        'Baseball Caps': 'https://www.amazon.com/gp/new-releases/sporting-goods/374749011/',
        'Novelty Headwear': 'https://www.amazon.com/gp/new-releases/sporting-goods/2515124011/',
        'Scrub Caps': 'https://www.amazon.com/gp/new-releases/sporting-goods/2515126011/',
        'Skullies & Beanies': 'https://www.amazon.com/gp/new-releases/sporting-goods/374752011/',
        'Visors': 'https://www.amazon.com/gp/new-releases/sporting-goods/374753011/',

        'Cell Phone Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/3209246011/',

        'Clothing': 'https://www.amazon.com/gp/new-releases/sporting-goods/374742011/',
        'Jackets': 'https://www.amazon.com/gp/new-releases/sporting-goods/3203998011/',
        'Jerseys': 'https://www.amazon.com/gp/new-releases/sporting-goods/3203999011/',
        'Pants': 'https://www.amazon.com/gp/new-releases/sporting-goods/3204000011/',
        'Polo Shirts': 'https://www.amazon.com/gp/new-releases/sporting-goods/3204001011/',
        'Shorts': 'https://www.amazon.com/gp/new-releases/sporting-goods/3204002011/',
        'Sweaters': 'https://www.amazon.com/gp/new-releases/sporting-goods/3204003011/',
        'Sweatshirts & Hoodies': 'https://www.amazon.com/gp/new-releases/sporting-goods/3204004011/',
        'T - Shirts': 'https://www.amazon.com/gp/new-releases/sporting-goods/3204005011/',
        'Baby Clothing': 'https://www.amazon.com/gp/new-releases/sporting-goods/3204006011/',

        'Clothing Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/2431377011/',
        'Belts': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768996011/',
        'Buckles': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768997011/',
        'Caps & Hats': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768995011/',
        'Headbands': 'https://www.amazon.com/gp/new-releases/sporting-goods/2515125011/',
        'Sleeve Patches': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768999011/',
        'Socks': 'https://www.amazon.com/gp/new-releases/sporting-goods/3204007011/',
        'Scarves': 'https://www.amazon.com/gp/new-releases/sporting-goods/5768998011/',
        'Sunglasses': 'https://www.amazon.com/gp/new-releases/sporting-goods/374744011/',
        'Ties': 'https://www.amazon.com/gp/new-releases/sporting-goods/374772011/',
        'Wristbands': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769000011/',

        'Electronics': 'https://www.amazon.com/gp/new-releases/sporting-goods/2311740011/',
        'Binoculars': 'https://www.amazon.com/gp/new-releases/sporting-goods/375521011/',
        'Computer Mice': 'https://www.amazon.com/gp/new-releases/sporting-goods/374848011/',
        'Computer Mousepads': 'https://www.amazon.com/gp/new-releases/sporting-goods/374849011/',
        'Computer Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/3318643011/',
        'Headphones': 'https://www.amazon.com/gp/new-releases/sporting-goods/3209247011/',
        'MP3 Player Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/3209248011/',
        'Tablet Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/13227293011/',

        'Footwear': 'https://www.amazon.com/gp/new-releases/sporting-goods/374747011/',
        'Sandals': 'https://www.amazon.com/gp/new-releases/sporting-goods/2309437011/',
        'Slippers': 'https://www.amazon.com/gp/new-releases/sporting-goods/2309435011/',
        'Sneakers': 'https://www.amazon.com/gp/new-releases/sporting-goods/2309436011/',
        'Shoelaces': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769025011/',

        'Gameday & Tailgating': 'https://www.amazon.com/gp/new-releases/sporting-goods/375518011/',
        'Aprons': 'https://www.amazon.com/gp/new-releases/sporting-goods/375520011/',
        'Binoculars': 'https://www.amazon.com/gp/new-releases/sporting-goods/375521011/',
        'Canopies': 'https://www.amazon.com/gp/new-releases/sporting-goods/375522011/',
        'Coolers': 'https://www.amazon.com/gp/new-releases/sporting-goods/375523011/',
        'Folding Chairs': 'https://www.amazon.com/gp/new-releases/sporting-goods/721272011/',
        'Grills & Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/375528011/',
        'Paper Cups & Plates': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769026011/',
        'Rally Towels': 'https://www.amazon.com/gp/new-releases/sporting-goods/5813568011/',
        'Stadium Noisemakers': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769029011/',
        'Stadium Seats & Cushions': 'https://www.amazon.com/gp/new-releases/sporting-goods/375529011/',
        'Tailgater Mats': 'https://www.amazon.com/gp/new-releases/sporting-goods/375531011/',

        'Golf Store': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769001011/',
        'Golf Equipment': 'https://www.amazon.com/gp/new-releases/sporting-goods/374809011/',
        'Polo Shirts': 'https://www.amazon.com/gp/new-releases/sporting-goods/3204001011/',
        'Visors': 'https://www.amazon.com/gp/new-releases/sporting-goods/374753011/',

        'Home & Kitchen': 'https://www.amazon.com/gp/new-releases/sporting-goods/374819011/',
        'Artwork': 'https://www.amazon.com/gp/new-releases/sporting-goods/2311723011/',
        'Bath': 'https://www.amazon.com/gp/new-releases/sporting-goods/2423130011/',
        'Bedding': 'https://www.amazon.com/gp/new-releases/sporting-goods/374822011/',
        'Decor': 'https://www.amazon.com/gp/new-releases/sporting-goods/2311724011/',
        'Furniture': 'https://www.amazon.com/gp/new-releases/sporting-goods/374860011/',
        'Kitchen & Dining': 'https://www.amazon.com/gp/new-releases/sporting-goods/374875011/',

        'Jewelry & Watches': 'https://www.amazon.com/gp/new-releases/sporting-goods/374916011/',
        'Bracelets': 'https://www.amazon.com/gp/new-releases/sporting-goods/374917011/',
        'Charms': 'https://www.amazon.com/gp/new-releases/sporting-goods/374918011/',
        'Cuff Links': 'https://www.amazon.com/gp/new-releases/sporting-goods/5813574011/',
        'Earrings': 'https://www.amazon.com/gp/new-releases/sporting-goods/374919011/',
        'Necklaces & Pendants': 'https://www.amazon.com/gp/new-releases/sporting-goods/374924011/',
        'Rings': 'https://www.amazon.com/gp/new-releases/sporting-goods/374925011/',
        'Watches': 'https://www.amazon.com/gp/new-releases/sporting-goods/374926011/',

        'Office Products': 'https://www.amazon.com/gp/new-releases/sporting-goods/2309018011/',
        'Backrests': 'https://www.amazon.com/gp/new-releases/sporting-goods/374821011/',
        'Badge Holders': 'https://www.amazon.com/gp/new-releases/sporting-goods/5813557011/',
        'Briefcases': 'https://www.amazon.com/gp/new-releases/sporting-goods/5813558011/',
        'Calendars & Planners': 'https://www.amazon.com/gp/new-releases/sporting-goods/374836011/',
        'Clipboards': 'https://www.amazon.com/gp/new-releases/sporting-goods/5813559011/',
        'Desk Caddies': 'https://www.amazon.com/gp/new-releases/sporting-goods/374853011/',
        'Desk Lamps': 'https://www.amazon.com/gp/new-releases/sporting-goods/374854011/',
        'Desk Pads & Blotters': 'https://www.amazon.com/gp/new-releases/sporting-goods/5813560011/',
        'Letter Openers': 'https://www.amazon.com/gp/new-releases/sporting-goods/5813561011/',
        'Memo Boards': 'https://www.amazon.com/gp/new-releases/sporting-goods/5813562011/',
        'Notebooks': 'https://www.amazon.com/gp/new-releases/sporting-goods/5813563011/',
        'Notepad Holders': 'https://www.amazon.com/gp/new-releases/sporting-goods/374855011/',
        'Notepads': 'https://www.amazon.com/gp/new-releases/sporting-goods/374856011/',
        'Office Chairs': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769032011/',
        'Paper Cubes': 'https://www.amazon.com/gp/new-releases/sporting-goods/5813564011/',
        'Paperweights': 'https://www.amazon.com/gp/new-releases/sporting-goods/374857011/',
        'Pencil Holders': 'https://www.amazon.com/gp/new-releases/sporting-goods/5813565011/',
        'Pencils': 'https://www.amazon.com/gp/new-releases/sporting-goods/374840011/',
        'Pens': 'https://www.amazon.com/gp/new-releases/sporting-goods/374841011/',
        'Staplers': 'https://www.amazon.com/gp/new-releases/sporting-goods/5813566011/',
        'Waste Baskets': 'https://www.amazon.com/gp/new-releases/sporting-goods/374915011/',
        'Wrapping Paper': 'https://www.amazon.com/gp/new-releases/sporting-goods/5813567011/',

        'Patio, Lawn & Garden': 'https://www.amazon.com/gp/new-releases/sporting-goods/374893011/',
        'Can Coolers': 'https://www.amazon.com/gp/new-releases/sporting-goods/374880011/',
        'Canopies': 'https://www.amazon.com/gp/new-releases/sporting-goods/375522011/',
        'Coolers': 'https://www.amazon.com/gp/new-releases/sporting-goods/375523011/',
        'Grills & Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/375528011/',
        'Outdoor Flags': 'https://www.amazon.com/gp/new-releases/sporting-goods/721290011/',
        'Outdoor Pennants': 'https://www.amazon.com/gp/new-releases/sporting-goods/374896011/',
        'Stepping Stones': 'https://www.amazon.com/gp/new-releases/sporting-goods/374872011/',
        'Street Signs': 'https://www.amazon.com/gp/new-releases/sporting-goods/374907011/',
        'Wind Chimes': 'https://www.amazon.com/gp/new-releases/sporting-goods/374873011/',
        'Wind Socks': 'https://www.amazon.com/gp/new-releases/sporting-goods/721292011/',
        'Wind Spinners & Wheels': 'https://www.amazon.com/gp/new-releases/sporting-goods/374874011/',
        'Outdoor Statues': 'https://www.amazon.com/gp/new-releases/sporting-goods/3209249011/',
        'Outdoor Lighting': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769030011/',
        'Outdoor Thermometers': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769031011/',

        'Pet Gear': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769002011/',
        'Pet Bandanas': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769003011/',
        'Pet Beds': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769004011/',
        'Pet Bowls': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769005011/',
        'Pet Clothing': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769006011/',
        'Pet Collars & Harnesses': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769010011/',
        'Pet ID Tags': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769013011/',
        'Pet Jerseys': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769009011/',
        'Pet Leashes': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769014011/',
        'Pet Mats': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769015011/',

        'Sports Collectibles': 'https://www.amazon.com/gp/new-releases/sporting-goods/3250697011/',
        'Balls': 'https://www.amazon.com/gp/new-releases/sporting-goods/3311044011/',
        'Baseball Bases': 'https://www.amazon.com/gp/new-releases/sporting-goods/5395827011/',
        'Bats': 'https://www.amazon.com/gp/new-releases/sporting-goods/3311045011/',
        'Bobble Heads': 'https://www.amazon.com/gp/new-releases/sporting-goods/3311046011/',
        'Books': 'https://www.amazon.com/gp/new-releases/sporting-goods/3311047011/',
        'Clothing & Uniforms': 'https://www.amazon.com/gp/new-releases/sporting-goods/7702506011/',
        'Cut Signatures': 'https://www.amazon.com/gp/new-releases/sporting-goods/5931158011/',
        'Diecast Cars': 'https://www.amazon.com/gp/new-releases/sporting-goods/7702514011/',
        'Equipment Travel Bags': 'https://www.amazon.com/gp/new-releases/sporting-goods/7702515011/',
        'Experience Tickets': 'https://www.amazon.com/gp/new-releases/sporting-goods/5263625011/',
        'Figurines': 'https://www.amazon.com/gp/new-releases/sporting-goods/7702516011/',
        'Flags & Banners': 'https://www.amazon.com/gp/new-releases/sporting-goods/3311048011/',
        'Gloves': 'https://www.amazon.com/gp/new-releases/sporting-goods/3311051011/',
        'Golf Clubs': 'https://www.amazon.com/gp/new-releases/sporting-goods/3311052011/',
        'Hats': 'https://www.amazon.com/gp/new-releases/sporting-goods/3311053011/',
        'Helmets': 'https://www.amazon.com/gp/new-releases/sporting-goods/3311054011/',
        'Hockey Pucks': 'https://www.amazon.com/gp/new-releases/sporting-goods/3311057011/',
        'Hockey Sticks & Blades': 'https://www.amazon.com/gp/new-releases/sporting-goods/3311058011/',
        'Jerseys': 'https://www.amazon.com/gp/new-releases/sporting-goods/3311061011/',
        'Lineup Cards': 'https://www.amazon.com/gp/new-releases/sporting-goods/5395826011/',
        'Magazines': 'https://www.amazon.com/gp/new-releases/sporting-goods/3311062011/',
        'Personal Checks': 'https://www.amazon.com/gp/new-releases/sporting-goods/5395829011/',
        'Photographs': 'https://www.amazon.com/gp/new-releases/sporting-goods/3311063011/',
        'Postcards & Index Cards': 'https://www.amazon.com/gp/new-releases/sporting-goods/3311064011/',
        'Prints & Posters': 'https://www.amazon.com/gp/new-releases/sporting-goods/3311067011/',
        'Publications & Media': 'https://www.amazon.com/gp/new-releases/sporting-goods/7702507011/',
        'Shoes': 'https://www.amazon.com/gp/new-releases/sporting-goods/3311068011/',
        'Stadium Components': 'https://www.amazon.com/gp/new-releases/sporting-goods/5395825011/',
        'Ticket Stubs': 'https://www.amazon.com/gp/new-releases/sporting-goods/3311069011/',
        'Trading Cards': 'https://www.amazon.com/gp/new-releases/sporting-goods/3311070011/',
        'Trophies': 'https://www.amazon.com/gp/new-releases/sporting-goods/5395823011/',

        'Sports Equipment': 'https://www.amazon.com/gp/new-releases/sporting-goods/374927011/',
        'Baseball Equipment': 'https://www.amazon.com/gp/new-releases/sporting-goods/2311325011/',
        'Basketball Equipment': 'https://www.amazon.com/gp/new-releases/sporting-goods/2311328011/',
        'Football Equipment': 'https://www.amazon.com/gp/new-releases/sporting-goods/2311326011/',
        'Golf Equipment': 'https://www.amazon.com/gp/new-releases/sporting-goods/374809011/',
        'Hockey Equipment': 'https://www.amazon.com/gp/new-releases/sporting-goods/2311329011/',
        'Soccer Equipment': 'https://www.amazon.com/gp/new-releases/sporting-goods/2311327011/',
        'Tennis Equipment': 'https://www.amazon.com/gp/new-releases/sporting-goods/374943011/',

        'Sports Souvenirs': 'https://www.amazon.com/gp/new-releases/sporting-goods/374783011/',
        'Baseball Bats': 'https://www.amazon.com/gp/new-releases/sporting-goods/374929011/',
        'Event Programs': 'https://www.amazon.com/gp/new-releases/sporting-goods/374792011/',
        'Fan Packs': 'https://www.amazon.com/gp/new-releases/sporting-goods/375524011/',
        'Hard Hats': 'https://www.amazon.com/gp/new-releases/sporting-goods/374751011/',
        'Helmets': 'https://www.amazon.com/gp/new-releases/sporting-goods/3409906011/',
        'Key Chains': 'https://www.amazon.com/gp/new-releases/sporting-goods/374793011/',
        'Magnets': 'https://www.amazon.com/gp/new-releases/sporting-goods/374796011/',
        'Memorabilia Display & Storage': 'https://www.amazon.com/gp/new-releases/sporting-goods/2358921011/',
        'Pennants': 'https://www.amazon.com/gp/new-releases/sporting-goods/374798011/',
        'Photo Baseball Bats': 'https://www.amazon.com/gp/new-releases/sporting-goods/374799011/',
        'Photo Baseballs': 'https://www.amazon.com/gp/new-releases/sporting-goods/374800011/',
        'Photomints': 'https://www.amazon.com/gp/new-releases/sporting-goods/374801011/',
        'Pins': 'https://www.amazon.com/gp/new-releases/sporting-goods/374803011/',
        'Tailgater Mats': 'https://www.amazon.com/gp/new-releases/sporting-goods/375531011/',
        'Trading Cards': 'https://www.amazon.com/gp/new-releases/sporting-goods/374806011/',
        'Water Globes': 'https://www.amazon.com/gp/new-releases/sporting-goods/374807011/',

        'Tools & Home Improvement': 'https://www.amazon.com/gp/new-releases/sporting-goods/2309443011/',
        'Cabinet & Furniture Knobs': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769033011/',
        'Hand Tools': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769034011/',
        'Lamps': 'https://www.amazon.com/gp/new-releases/sporting-goods/721274011/',
        'Lighters': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769035011/',
        'Mailboxes': 'https://www.amazon.com/gp/new-releases/sporting-goods/374895011/',
        'Night Lights': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769036011/',
        'Tape Measures': 'https://www.amazon.com/gp/new-releases/sporting-goods/5769037011/',
        'Wallpaper': 'https://www.amazon.com/gp/new-releases/sporting-goods/374914011/',

        'Toys & Game Room': 'https://www.amazon.com/gp/new-releases/sporting-goods/375519011/',
        'Billiards': 'https://www.amazon.com/gp/new-releases/sporting-goods/374833011/',
        'Bobbleheads': 'https://www.amazon.com/gp/new-releases/sporting-goods/375537011/',
        'Darts & Dartboards': 'https://www.amazon.com/gp/new-releases/sporting-goods/374850011/',
        'Games': 'https://www.amazon.com/gp/new-releases/sporting-goods/721297011/',
        'Poker': 'https://www.amazon.com/gp/new-releases/sporting-goods/374901011/',
        'Toy Figures': 'https://www.amazon.com/gp/new-releases/sporting-goods/375539011/',
        'Toy Vehicles': 'https://www.amazon.com/gp/new-releases/sporting-goods/375540011/',
        'Tailgating Toss Games': 'https://www.amazon.com/gp/new-releases/sporting-goods/5893732011/',

        'Video Games & Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/3209250011/',

        'Outdoor Recreation': 'https://www.amazon.com/gp/new-releases/sporting-goods/706814011/',

        'Outdoor Clothing': 'https://www.amazon.com/gp/new-releases/sporting-goods/11443874011/',
        'Men': 'https://www.amazon.com/gp/new-releases/sporting-goods/11443875011/',
        'Women': 'https://www.amazon.com/gp/new-releases/sporting-goods/11443923011/',
        'Boys': 'https://www.amazon.com/gp/new-releases/sporting-goods/11443976011/',
        'Girls': 'https://www.amazon.com/gp/new-releases/sporting-goods/11444022011/',

        'Camping & Hiking': 'https://www.amazon.com/gp/new-releases/sporting-goods/3400371/',
        'Backpacks & Bags': 'https://www.amazon.com/gp/new-releases/sporting-goods/3400391/',
        'Tents & Shelters': 'https://www.amazon.com/gp/new-releases/sporting-goods/10208056011/',
        'Sleeping Bags & Camp Bedding': 'https://www.amazon.com/gp/new-releases/sporting-goods/3401611/',
        'Camp Kitchen': 'https://www.amazon.com/gp/new-releases/sporting-goods/2204505011/',
        'Camping Furniture': 'https://www.amazon.com/gp/new-releases/sporting-goods/3400781/',
        'Clothing': 'https://www.amazon.com/gp/new-releases/sporting-goods/2371054011/',
        'Footwear & Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/2204475011/',
        'Hydration & Filtration': 'https://www.amazon.com/gp/new-releases/sporting-goods/2204506011/',
        'Knives & Tools': 'https://www.amazon.com/gp/new-releases/sporting-goods/3400851/',
        'Lights & Lanterns': 'https://www.amazon.com/gp/new-releases/sporting-goods/3401301/',
        'Navigation & Electronics': 'https://www.amazon.com/gp/new-releases/sporting-goods/10208058011/',
        'Personal Care': 'https://www.amazon.com/gp/new-releases/sporting-goods/3401541/',
        'Safety & Survival': 'https://www.amazon.com/gp/new-releases/sporting-goods/3401081/',
        'Trekking Poles': 'https://www.amazon.com/gp/new-releases/sporting-goods/3401281/',

        'Climbing': 'https://www.amazon.com/gp/new-releases/sporting-goods/3402401/',
        'Rope, Cord & Webbing': 'https://www.amazon.com/gp/new-releases/sporting-goods/3402821/',
        'Harnesses': 'https://www.amazon.com/gp/new-releases/sporting-goods/3402661/',
        'Belay & Rigging': 'https://www.amazon.com/gp/new-releases/sporting-goods/3402481/',
        'Carabiners & Quickdraws': 'https://www.amazon.com/gp/new-releases/sporting-goods/3402541/',
        'Footwear': 'https://www.amazon.com/gp/new-releases/sporting-goods/13315711/',
        'Clothing': 'https://www.amazon.com/gp/new-releases/sporting-goods/2371050011/',
        'Helmets': 'https://www.amazon.com/gp/new-releases/sporting-goods/3402801/',
        'Climbing Protection': 'https://www.amazon.com/gp/new-releases/sporting-goods/10208059011/',
        'Mountaineering & Ice Equipment': 'https://www.amazon.com/gp/new-releases/sporting-goods/3402691/',
        'Bouldering & Wall Equipment': 'https://www.amazon.com/gp/new-releases/sporting-goods/10208061011/',

        'Cycling': 'https://www.amazon.com/gp/new-releases/sporting-goods/3403201/',
        'Car Racks, Transportation & Storage': 'https://www.amazon.com/gp/new-releases/sporting-goods/6389522011/',
        'Bikes': 'https://www.amazon.com/gp/new-releases/sporting-goods/1265458011/',
        'Kids Bikes & Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/2346793011/',
        'Clothing': 'https://www.amazon.com/gp/new-releases/sporting-goods/2371051011/',
        'Parts & Components': 'https://www.amazon.com/gp/new-releases/sporting-goods/3404731/',
        'Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/3403211/',
        'Tires & Tubes': 'https://www.amazon.com/gp/new-releases/sporting-goods/6388965011/',
        'Bike Racks & Bags': 'https://www.amazon.com/gp/new-releases/sporting-goods/6389515011/',
        'Helmets & Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/6389202011/',
        'Wheels & Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/6389156011/',
        'Bike Frames': 'https://www.amazon.com/gp/new-releases/sporting-goods/1266090011/',
        'Footwear': 'https://www.amazon.com/gp/new-releases/sporting-goods/3404251/',
        'Bike Tools & Maintenance': 'https://www.amazon.com/gp/new-releases/sporting-goods/3405541/',
        'Cycling Electronics': 'https://www.amazon.com/gp/new-releases/sporting-goods/5393951011/',
        'Protective Gear': 'https://www.amazon.com/gp/new-releases/sporting-goods/1265463011/',
        'Hydration': 'https://www.amazon.com/gp/new-releases/sporting-goods/6389203011/',
        'Bike Trainers & Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/6389526011/',
        'Child Seats & Cargo Trailers': 'https://www.amazon.com/gp/new-releases/sporting-goods/6389519011/',
        'BMX': 'https://www.amazon.com/gp/new-releases/sporting-goods/3403591/',

        'Skates, Skateboards & Scooters': 'https://www.amazon.com/gp/new-releases/sporting-goods/11051398011/',
        'Skateboarding': 'https://www.amazon.com/gp/new-releases/sporting-goods/3416111/',
        'Scooters & Equipment': 'https://www.amazon.com/gp/new-releases/sporting-goods/11063781/',
        'Inline & Roller Skating': 'https://www.amazon.com/gp/new-releases/sporting-goods/3416551/',

        'Water Sports': 'https://www.amazon.com/gp/new-releases/sporting-goods/11051399011/',
        'Canoeing': 'https://www.amazon.com/gp/new-releases/sporting-goods/2345540011/',
        'Kayaking': 'https://www.amazon.com/gp/new-releases/sporting-goods/2345546011/',
        'Diving & Snorkeling': 'https://www.amazon.com/gp/new-releases/sporting-goods/3406281/',
        'Stand - Up Paddleboarding': 'https://www.amazon.com/gp/new-releases/sporting-goods/3204434011/',
        'Surfing': 'https://www.amazon.com/gp/new-releases/sporting-goods/3418471/',
        'Waterskiing & Towsports': 'https://www.amazon.com/gp/new-releases/sporting-goods/4201151/',
        'Windsurfing': 'https://www.amazon.com/gp/new-releases/sporting-goods/3421611/',
        'Water Sports Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/11030588011/',

        'Winter Sports': 'https://www.amazon.com/gp/new-releases/sporting-goods/2204518011/',
        'Skiing': 'https://www.amazon.com/gp/new-releases/sporting-goods/2342470011/',
        'Snowboarding': 'https://www.amazon.com/gp/new-releases/sporting-goods/2342471011/',
        'Sledding': 'https://www.amazon.com/gp/new-releases/sporting-goods/3417621/',
        'Snowmobiling': 'https://www.amazon.com/gp/new-releases/sporting-goods/3417681/',
        'Snowshoeing': 'https://www.amazon.com/gp/new-releases/sporting-goods/2342472011/',
        'Ice Skating': 'https://www.amazon.com/gp/new-releases/sporting-goods/3416451/',
        'Winter Sports Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/11030589011/',

        'Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/11051400011/',
        'Accessory & Keychain Carabiners': 'https://www.amazon.com/gp/new-releases/sporting-goods/10184604011/',
        'Car Racks & Carriers': 'https://www.amazon.com/gp/new-releases/sporting-goods/491437011/',
        'Electronics': 'https://www.amazon.com/gp/new-releases/sporting-goods/219367011/',
        'Gear Repair Equipment': 'https://www.amazon.com/gp/new-releases/sporting-goods/10208184011/',
        'Inflation Devices & Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/2341089011/',
        'Paracord': 'https://www.amazon.com/gp/new-releases/sporting-goods/6152953011/',
        'Reflective Gear': 'https://www.amazon.com/gp/new-releases/sporting-goods/3395071/',
        'Sports Medicine': 'https://www.amazon.com/gp/new-releases/sporting-goods/3422351/',
        'Sports Sunglasses': 'https://www.amazon.com/gp/new-releases/sporting-goods/2204481011/',
        'Sports Water Bottle Accessories': 'https://www.amazon.com/gp/new-releases/sporting-goods/2403094011/',
        'Sports Water Bottles': 'https://www.amazon.com/gp/new-releases/sporting-goods/3395091/',
        'Traction Cleats': 'https://www.amazon.com/gp/new-releases/sporting-goods/5160160011/',
    }
}
